[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "folium>=0.20.0",
    "pandas>=2.3.1",
    "plotly>=6.2.0",
    "streamlit-folium>=0.25.1",
    "streamlit>=1.47.1",
    "numpy>=2.3.2",
    "scipy>=1.16.1",
    "scikit-learn>=1.7.1",
]
